version: "3.3"

services:
  webapp:
    image: web-app:latest
    restart: always
    container_name: web-app
    ports:
      - 3000:80
    working_dir: /app
    environment:
      - GOOGLE_API_KEY=GOOGLE_API_KEY
