name: Build master
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  merge-PR:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: lukeshaydocker/route-rating-web-app
      SHA: ${GITHUB_SHA::7}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn --disable-progress
      - run: yarn build --disable-progress
      - run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - run: docker build -t ${{ env.DOCKER_REPO }}:${{ env.SHA }} -t ${{ env.DOCKER_REPO }}:latest .
      - run: docker push ${{ env.DOCKER_REPO }}:${{ env.SHA }}
      - run: docker push ${{ env.DOCKER_REPO }}:latest
      